server:
  tomcat:
    uri-encoding: utf-8
    threads:
      max: 1000
      min-spare: 30
  port: 9292
  servlet:
    context-path: /bee-admin
    session:
      cookie:
        http-only: true

# knife4j
knife4j:
  basic:
    enable: false
    username: admin
    password: bee
  enable: true
  setting:
    enableFooter: true

# spring
spring:
  application:
    name: bee-admin
  profiles:
    active: dev
  messages:
    encoding: UTF-8
    basename: i18n/message
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      file-size-threshold: 100MB
      max-request-size: 100MB
      enabled: true

# bee 是否开启缓存
bee:
  redis:
    enable: false

# mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.bee.modules.*.entity
  global-config:
    db-config:
      id-type: assign_id
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
