
spring:
  redis:
    host: qcloud.realpluto.cn
    port: 6379
    password: slg2020/REDIS
    connect-timeout: 6000ms # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms     # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10       # 连接池中的最大空闲连接
        min-idle: 5        # 连接池中的最小空闲连接
  datasource:
    druid:
      #MySQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://qcloud.realpluto.cn:3306/bee?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: bee
      password: bee2020$%
logging:
  level:
    root: debug